# Automatisch erzeugt von tools/build_site.py
    location = /produkte.html { return 301 /wps-moertelpumpe$is_args$args; }
    location = /anwendung-untermoerteln.html { return 301 /untermoerteln-holzschwellen$is_args$args; }
    location = /anwendung-stahlzargen.html { return 301 /stahlzargen-einmoerteln$is_args$args; }
    location = /anwendung-naturstein.html { return 301 /natursteinmauer-verfugen$is_args$args; }
    location = /anwendung-klinker.html { return 301 /klinker-verfugen$is_args$args; }
    location = /anwendung-betonfugen.html { return 301 /betonfugen-ausmoerteln$is_args$args; }
    location = /anwendung-spannbeton.html { return 301 /deckenfugen-ausmoerteln$is_args$args; }
    location = /anwendung-maueranker.html { return 301 /maueranker-verpressen$is_args$args; }
    location = /anwendung-daemmplatten.html { return 301 /daemmplatten-kleben$is_args$args; }
    location = /moertel-bedarf-rechner.html { return 301 /moertelrechner$is_args$args; }
    location = /anwendung-fugen.html { return 301 /natursteinmauer-verfugen$is_args$args; }
